#!/usr/bin/env bash
# OpenClaw needs an interactive onboarding pass before its gateway can start,
# so this environment uses the custom run.sh archetype instead of the generic
# Compose dispatcher. Lifecycle semantics otherwise match the rest of the repo.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$SCRIPT_DIR"

POLICY="${REBUILD_POLICY:-FAST}"
DOCKER="${DOCKER_CMD:-docker}"

# Defaults also make a direct ./run.sh invocation work without a generated
# .env. A real .env, when present, overrides all of them.
CONTAINER_NAME="${CONTAINER_NAME:-openclaw}"
OPENCLAW_GATEWAY_PORT="${OPENCLAW_GATEWAY_PORT:-18789}"
OPENCLAW_BRIDGE_PORT="${OPENCLAW_BRIDGE_PORT:-18790}"
OPENCLAW_MSTEAMS_PORT="${OPENCLAW_MSTEAMS_PORT:-3978}"
OPENCLAW_GATEWAY_BIND="${OPENCLAW_GATEWAY_BIND:-lan}"
OPENCLAW_TZ="${OPENCLAW_TZ:-UTC}"
OPENCLAW_LOCAL_IMAGE="${OPENCLAW_LOCAL_IMAGE:-openclaw-with-clis:latest}"
OPENCLAW_GATEWAY_TOKEN="${OPENCLAW_GATEWAY_TOKEN:-}"

if [ -f .env ]; then
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a
fi

export CONTAINER_NAME OPENCLAW_GATEWAY_PORT OPENCLAW_BRIDGE_PORT
export OPENCLAW_MSTEAMS_PORT OPENCLAW_GATEWAY_BIND OPENCLAW_TZ
export OPENCLAW_LOCAL_IMAGE OPENCLAW_GATEWAY_TOKEN

compose() {
    "$DOCKER" compose "$@"
}

refresh_desktop_and_info() {
    bash "$REPO_DIR/lib/run-install-desktop.sh" "$SCRIPT_DIR" >/dev/null 2>&1 || true
    bash "$REPO_DIR/lib/run-info.sh" "$SCRIPT_DIR" list
}

case "$POLICY" in
    STOP)
        echo "🛑 [STOP] Pausing the OpenClaw gateway..."
        compose stop openclaw-gateway 2>/dev/null || true
        exit 0
        ;;
    TEARDOWN)
        echo "🗑️  [TEARDOWN] Removing OpenClaw containers (persistent volumes preserved)..."
        compose down 2>/dev/null || true
        bash "$REPO_DIR/lib/run-install-desktop.sh" "$SCRIPT_DIR" >/dev/null 2>&1 || true
        exit 0
        ;;
    CLEAN)
        echo "🧹 [CLEAN] Pulling OpenClaw and rebuilding the image with fresh Claude/Codex CLIs..."
        if ! compose build --pull --no-cache; then
            echo "❌ Build failed — leaving the existing gateway untouched." >&2
            exit 1
        fi
        ;;
    FAST)
        if ! "$DOCKER" image inspect "$OPENCLAW_LOCAL_IMAGE" >/dev/null 2>&1; then
            echo "🐳 No local OpenClaw+CLIs image yet — building it now..."
            compose build
        fi
        ;;
    *)
        echo "❌ Unsupported REBUILD_POLICY: $POLICY" >&2
        exit 2
        ;;
esac

bash "$SCRIPT_DIR/pre-deploy.sh"
# Pick up a token generated by pre-deploy.sh.
set -a
# shellcheck disable=SC1091
source .env
set +a
export OPENCLAW_GATEWAY_TOKEN

# Test the persistent config through the same image/user/mounts as the real
# gateway. On first deploy, hand the terminal directly to official onboarding.
if ! compose run --rm --no-deps --entrypoint sh openclaw-gateway \
    -c 'test -s /home/node/.openclaw/openclaw.json'; then
    echo "🦞 First deploy — starting OpenClaw onboarding..."
    bash "$SCRIPT_DIR/scripts/onboard.sh"
fi

# Keep the Docker-specific gateway mode/bind and safe Control UI origins in
# sync after onboarding. Include the current LAN IP so another machine on the
# same network can use the published dashboard without enabling host-header
# origin fallback.
HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
if [ -z "$HOST_IP" ]; then
    HOST_IP="$(ip route get 1 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i=="src") {print $(i+1); exit}}' || true)"
fi
HOST_IP="${HOST_IP:-127.0.0.1}"
CONFIG_JSON="[{\"path\":\"gateway.mode\",\"value\":\"local\"},{\"path\":\"gateway.bind\",\"value\":\"${OPENCLAW_GATEWAY_BIND}\"},{\"path\":\"gateway.controlUi.allowedOrigins\",\"value\":[\"http://localhost:${OPENCLAW_GATEWAY_PORT}\",\"http://127.0.0.1:${OPENCLAW_GATEWAY_PORT}\",\"http://${HOST_IP}:${OPENCLAW_GATEWAY_PORT}\"]}]"
compose run --rm --no-deps --entrypoint node openclaw-gateway \
    dist/index.js config set --batch-json "$CONFIG_JSON"

if [ "$POLICY" = "CLEAN" ]; then
    echo "🛑 Fresh image and configuration ready — recreating the gateway..."
    compose down 2>/dev/null || true
    "$DOCKER" image prune -f >/dev/null 2>&1 || true
fi

compose up -d openclaw-gateway
refresh_desktop_and_info
