services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PIHOLE_WEB_PORT:-8080}:80/tcp"
    environment:
      - TZ=${TZ:-Asia/Singapore}
      - WEBPASSWORD=${FTLCONF_webserver_api_password}
      - FTLCONF_dns_upstreams=1.1.1.1;1.0.0.1
    volumes:
      - './etc-pihole:/etc/pihole'
    networks:
      pihole_wg_net:
        ipv4_address: ${PIHOLE_INTERNAL_IP:-172.20.0.2}
    restart: unless-stopped

  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:latest
    depends_on:
      - pihole
    environment:
      - TZ=${TZ:-Asia/Singapore}
      - WG_HOST=${WG_HOST}
      - WG_DEFAULT_DNS=${PIHOLE_INTERNAL_IP:-172.20.0.2}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS:-0.0.0.0/0}
      - WG_POST_UP=:
      - WG_PRE_DOWN=:
    volumes:
      - './etc-wireguard:/etc/wireguard'
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

networks:
  pihole_wg_net:
    name: pihole_wg_network
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET:-172.20.0.0/16}