#!/bin/bash

# 1. Check if the active .env file exists (generated by your TUI script)
if [ ! -f .env ]; then
    echo "[ERROR] .env file not found! Please run your TUI configuration setup script first."
    exit 1
fi

# 2. Export variables from the .env file so this script can read them
export $(grep -v '^#' .env | xargs)

# 3. Ensure the local workspace volume directory exists on the host
mkdir -p "${HOST_WORKSPACE_VOLUME}"

# 4. Execute the Docker container using the dynamically injected variables
docker run -it \
  --privileged \
  -v "${HOST_USB_BUS_PATH}:/dev/bus/usb" \
  -e DISPLAY="${DISPLAY}" \
  -v "${HOST_X11_UNIX_PATH}:/tmp/.X11-unix" \
  --net=host \
  --device "${HOST_SOUND_DEVICE}" \
  -e PULSE_SERVER="unix:${HOST_PULSE_NATIVE_SOCKET}" \
  -v "${HOST_PULSE_NATIVE_SOCKET}:${HOST_PULSE_NATIVE_SOCKET}" \
  -v "${HOST_PULSE_COOKIE_PATH}:/root/.config/pulse/cookie" \
  -v "${HOST_WORKSPACE_VOLUME}:/workspace" \
  --name "${CONTAINER_NAME}" \
  --entrypoint "${CONTAINER_ENTRYPOINT_COMMAND}" \
  --rm \
  "${DOCKER_IMAGE_TAG}"